# Generated by Django 5.0.6 on 2024-07-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
