# Generated by Django 5.0.6 on 2024-07-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_estudiante_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='profesion',
            new_name='especialidad',
        ),
    ]
